# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prego.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from reportlab.pdfgen import canvas


class Ui_MainWindow(object):
   def exporter_pdf(self):
        n_fich = "ticket_caisse.pdf"
        c = canvas.Canvas(n_fich)

        # titre
        c.setFont("Helvetica-Bold", 16)
        c.drawString(100, 800, "MON SUPER MAGASIN")

        # contenu du tableau

        y = 750
        c.setFont("Helvetica", 12)
        for row in range(self.table_inventaire.rowCount()):
             article = self.table_inventaire.item(row, 0).text()
             prix = self.table_inventaire.item(row, 1).text()
        c.drawString(100, y, f"{article} : {prix}")
        y -=20

        if y < 50:
             c.showPage()
             y = 800
             #print("ticker generer avec succes")
        c = c.save()
        print("ticker generer avec succes")
        
   
   def suprimer(self):
        ligne_actuelle = self.table_inventaire.currentRow()
        
        if ligne_actuelle != -1:
             self.table_inventaire.removeRow(ligne_actuelle)
            
             self.calculer_total()
   def calculer_total(self):
         total_payer = 0.0
         for row in range(self.table_inventaire.rowCount()):
             sioss = self.table_inventaire.item(row, 1)
             if sioss is not None:
                 t_prix = sioss.text().replace("fcfa","").strip()
                 total_payer  += float(t_prix)
         self.afich_somme.setText(f"{total_payer:.2f}fcfa")     
      
   
   def action(self):
        
        # recuperation text de qline 
         nom = self.input_nom.text()
         prix = self.input_prix.text()
        # insertion de ligne 
         row = self.table_inventaire.rowCount()
         self.table_inventaire.insertRow(row)
        # transformation du text en objet  de tableau
         self.table_inventaire.setItem(row, 0, QtWidgets.QTableWidgetItem(nom))
         self.table_inventaire.setItem(row, 1, QtWidgets.QTableWidgetItem(str(prix) + "fcfa"))
         self.input_nom.clear()
         self.input_prix.clear()
         self.input_nom.setFocus()
         #self.calculer_total()
         self.calculer_total()
         self.exporter_pdf()
        
   def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(765, 600)
        MainWindow.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setStyleSheet("background-color: rgb(119, 118, 123);")
        self.groupBox_1.setObjectName("groupBox_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_nom = QtWidgets.QLineEdit(self.groupBox_1)
        self.input_nom.setStyleSheet("background-color: rgb(143, 240, 164);\n"
"background-color: rgb(153, 193, 241);")
        self.input_nom.setObjectName("input_nom")
        self.verticalLayout.addWidget(self.input_nom)
        self.label_1 = QtWidgets.QLabel(self.groupBox_1)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.input_prix = QtWidgets.QLineEdit(self.groupBox_1)
        self.input_prix.setStyleSheet("background-color: rgb(153, 193, 241);\n"
"background-color: rgb(153, 193, 241);")
        self.input_prix.setObjectName("input_prix")
        self.verticalLayout.addWidget(self.input_prix)
        self.label_2 = QtWidgets.QLabel(self.groupBox_1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_1.clicked.connect(self.action)
        self.pushButton_1.setStyleSheet("background-color: rgb(153, 193, 241);\n"
"background-color: rgb(153, 193, 241);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout.addWidget(self.pushButton_1)
        self.verticalLayout_2.addWidget(self.groupBox_1)
        self.table_inventaire = QtWidgets.QTableWidget(self.centralwidget)
        self.table_inventaire.setStyleSheet("alternate-background-color: rgb(143, 240, 164);\n"
"background-color: rgb(143, 240, 164);")
        self.table_inventaire.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_inventaire.setTabKeyNavigation(False)
        self.table_inventaire.setProperty("showDropIndicator", False)
        self.table_inventaire.setDragDropOverwriteMode(False)
        self.table_inventaire.setObjectName("table_inventaire")
        self.table_inventaire.setColumnCount(2)
        self.table_inventaire.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_inventaire.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_inventaire.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.table_inventaire)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.afich_somme = QtWidgets.QLineEdit(self.centralwidget)
        self.afich_somme.setObjectName("afich_somme")
        self.verticalLayout_2.addWidget(self.afich_somme)
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.clicked.connect(self.suprimer)
        self.pushButton_reset.setStyleSheet("background-color: rgb(237, 51, 59);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_2.addWidget(self.pushButton_reset)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 765, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

   def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_1.setTitle(_translate("MainWindow", "saisi d\'article"))
        self.label_1.setText(_translate("MainWindow", "nom"))
        self.label_2.setText(_translate("MainWindow", "prix"))
        self.pushButton_1.setText(_translate("MainWindow", "valider"))
        item = self.table_inventaire.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "article"))
        item = self.table_inventaire.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "prix"))
        self.label_3.setText(_translate("MainWindow", "\"TOTAL À PAYER:\""))
        self.afich_somme.setText(_translate("MainWindow", "0.00fcfa"))
        self.pushButton_reset.setText(_translate("MainWindow", "tout effacer"))
       
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
